service: nuggets-center

plugins:
  - serverless-esbuild # used for compiling/packaging the Typescript code
  - serverless-offline # used for local execution
  - serverless-ssm-fetch

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: ${opt:stage}
  timeout: 30   # repository wide Lambda timeout
  environment:  # repository wide Lambda env variables
    STAGE: ${self:provider.stage}

custom:
  esbuild:
    external:
      - jsdom
    packager: npm
  serverlessSsmFetch:
    DATABASE_URL: /nuggets-center/DATABASE_URL
    DIRECT_URL: /nuggets-center/DIRECT_URL

functions:
  # Serverless Framework specific syntax
  daily-scrape:
    handler: ./src/server/lambda/daily-scrape.handler
    events:
      - schedule:
          rate: cron(0 6 * * ? *) # every day at 6am UTC
          enabled: true
  weekly-scrape:
    handler: ./src/server/lambda/weekly-scrape.handler
    timeout: 10
    events:
      - schedule:
          rate: rate(7 days) # triggers every 7 days
          enabled: true
