import type { Metadata } from 'next'
import { ReactNode } from 'react'
import { Inter } from 'next/font/google'
import { TRPCProvider } from '@/components/providers/TRPCProvider'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: ReactNode }): ReactNode => {
    return (
        <html lang="en">
            <body className={inter.className}>
                <TRPCProvider>{children}</TRPCProvider>
            </body>
        </html>
    )
}

export default RootLayout
