name: Tests
on: 
    pull_request:
        branches:
            - main

env:
    DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
    DIRECT_URL: postgres://postgres:postgres@localhost:5432/postgres
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build
            - name: Run tests
              run: npm test
    integration-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/build
            - uses: KengoTODA/actions-setup-docker-compose@v1.2.3
              with:
                version: '2.14.2'
            - name: Run tests
              run: pnpm run test:int
